apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-eventpipeline
    url: postgres:5432
    user: eventpipeline
    secureJsonData:
      password: eventpipeline
    jsonData:
      database: eventpipeline
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
